export const navbarData = [
  {
    id: 1,
    navigationTitle: "ABOUT US",
    url: "/",
  },
  {
    id: 2,
    navigationTitle: "OUR STORIES",
    url: "/our-stories",
  },
  {
    id: 3,
    navigationTitle: "CONTACT",
    url: "/contact",
  },
  {
    id: 4,
    navigationTitle: "SHARE YOUR STORY",
    url: "/your-story",
  },
];

export const footerData = {
  author: "MINDFULLMEDIA",
};

export const teamMembers = [
  {
    id: 1,
    name: "Ola",
    surname: "Kawa",
    image: "team-members/member1.jpg",
    description:
      "Hi my name is Ola, I am a second year student at AMU in Poznań. Currently I am on Erasmus programme in Denmark. Everyone uses social media on a daily basis. Most of us don't even realise how much we are influenced by things that we see or read on various platforms. I believe that the bad side of social media is quite openly talked about, therefore we decided to focus on something different. We want to showcase that those platforms can have a good impact on one's mental health too.",
  },
  {
    id: 2,
    name: "Castro",
    surname: "Okorie",
    image: "team-members/member2.jpg",
    description:
      "Hi everyone, I'm Castro, a Creative Business student at Hogeschool Utrecht, originally from Nigeria. I love working with people from diverse backgrounds. I’m passionate about creativity, travel, and meaningful conversations, and I enjoy connecting ideas and people through various projects. Outside of school, I'm involved in entrepreneurial and creative ventures that push me to grow and see the world differently. I believe everyone has something unique to teach, and that's why it's so important to build communities like this one.",
  },
  {
    id: 3,
    name: "Tomek",
    surname: "Stróżyna",
    image: "team-members/member3.jpg",
    description:
      "Hi, I'm Tomek, and I study Management and Business Law at AMU in Poznań. I'm passionate about sports, reading - especially behavioral psychology and philosophy - and hiking in the mountains during summer. One quote I live by is from Marcus Aurelius: “The mind in itself has no needs... except those it creates itself”, which reminds me that we control our perceptions and reactions. Personally, I don't use any social media platforms, but I'm aware, how much of an influence they have on my generation.",
  },
  {
    id: 4,
    name: "Sandra",
    surname: "Dmowska",
    image: "team-members/member4.jpg",
    description:
      "Hi! I'm Sandra, and I study Management and Business Law and Finance, Audit, Investments. My main interests are: playing volleyball, cuddling with my cat and playing board/card/computer games with my family and friends. I'm chronically online, I'm fighting with my addiction, but at the same time I can name multiple ways how social media helped me at my lowest. That's why this project is close to my heart.",
  },
];

export const filtersData = {
  age: [
    { value: "Prefer not to say", label: "Prefer not to say" },
    { value: "0-14", label: "0-14" },
    { value: "15-18", label: "15-18" },
    { value: "19-22", label: "19-22" },
    { value: "23-25", label: "23-25" },
    { value: "26-35", label: "26-35" },
    { value: "36-50", label: "36-50" },
    { value: "50+", label: "50+" },
  ],
  gender: [
    { value: "Prefer not to say", label: "Prefer not to say" },
    { value: "Man", label: "Man" },
    { value: "Woman", label: "Woman" },
    { value: "Non-binary", label: "Non-binary" },
  ],
  sexuality: [
    { value: "Prefer not to say", label: "Prefer not to say" },
    { value: "Heterosexual", label: "Heterosexual" },
    { value: "Homosexual", label: "Homosexual" },
    { value: "Bisexual", label: "Bisexual" },
    { value: "Pansexual", label: "Pansexual" },
    { value: "Asexual", label: "Asexual" },
  ],
  nationality: [
    { value: "Prefer not to say", label: "Prefer not to say" },
    { value: "Afghan", label: "Afghan" },
    { value: "Albanian", label: "Albanian" },
    { value: "Algerian", label: "Algerian" },
    { value: "American", label: "American" },
    { value: "Andorran", label: "Andorran" },
    { value: "Angolan", label: "Angolan" },
    { value: "Antiguans", label: "Antiguans" },
    { value: "Argentinean", label: "Argentinean" },
    { value: "Armenian", label: "Armenian" },
    { value: "Australian", label: "Australian" },
    { value: "Austrian", label: "Austrian" },
    { value: "Azerbaijani", label: "Azerbaijani" },
    { value: "Bahamian", label: "Bahamian" },
    { value: "Bahraini", label: "Bahraini" },
    { value: "Bangladeshi", label: "Bangladeshi" },
    { value: "Barbadian", label: "Barbadian" },
    { value: "Barbudans", label: "Barbudans" },
    { value: "Batswana", label: "Batswana" },
    { value: "Belarusian", label: "Belarusian" },
    { value: "Belgian", label: "Belgian" },
    { value: "Belizean", label: "Belizean" },
    { value: "Beninese", label: "Beninese" },
    { value: "Bhutanese", label: "Bhutanese" },
    { value: "Bolivian", label: "Bolivian" },
    { value: "Bosnian", label: "Bosnian" },
    { value: "Brazilian", label: "Brazilian" },
    { value: "British", label: "British" },
    { value: "Bruneian", label: "Bruneian" },
    { value: "Bulgarian", label: "Bulgarian" },
    { value: "Burkinabe", label: "Burkinabe" },
    { value: "Burmese", label: "Burmese" },
    { value: "Burundian", label: "Burundian" },
    { value: "Cambodian", label: "Cambodian" },
    { value: "Cameroonian", label: "Cameroonian" },
    { value: "Canadian", label: "Canadian" },
    { value: "Cape Verdean", label: "Cape Verdean" },
    { value: "Central African", label: "Central African" },
    { value: "Chadian", label: "Chadian" },
    { value: "Chilean", label: "Chilean" },
    { value: "Chinese", label: "Chinese" },
    { value: "Colombian", label: "Colombian" },
    { value: "Comoran", label: "Comoran" },
    { value: "Congolese", label: "Congolese" },
    { value: "Costa Rican", label: "Costa Rican" },
    { value: "Croatian", label: "Croatian" },
    { value: "Cuban", label: "Cuban" },
    { value: "Cypriot", label: "Cypriot" },
    { value: "Czech", label: "Czech" },
    { value: "Danish", label: "Danish" },
    { value: "Djibouti", label: "Djibouti" },
    { value: "Dominican", label: "Dominican" },
    { value: "Dutch", label: "Dutch" },
    { value: "East Timorese", label: "East Timorese" },
    { value: "Ecuadorean", label: "Ecuadorean" },
    { value: "Egyptian", label: "Egyptian" },
    { value: "Emirian", label: "Emirian" },
    { value: "Equatorial Guinean", label: "Equatorial Guinean" },
    { value: "Eritrean", label: "Eritrean" },
    { value: "Estonian", label: "Estonian" },
    { value: "Ethiopian", label: "Ethiopian" },
    { value: "Fijian", label: "Fijian" },
    { value: "Filipino", label: "Filipino" },
    { value: "Finnish", label: "Finnish" },
    { value: "French", label: "French" },
    { value: "Gabonese", label: "Gabonese" },
    { value: "Gambian", label: "Gambian" },
    { value: "Georgian", label: "Georgian" },
    { value: "German", label: "German" },
    { value: "Ghanaian", label: "Ghanaian" },
    { value: "Greek", label: "Greek" },
    { value: "Grenadian", label: "Grenadian" },
    { value: "Guatemalan", label: "Guatemalan" },
    { value: "Guinea-Bissauan", label: "Guinea-Bissauan" },
    { value: "Guinean", label: "Guinean" },
    { value: "Guyanese", label: "Guyanese" },
    { value: "Haitian", label: "Haitian" },
    { value: "Herzegovinian", label: "Herzegovinian" },
    { value: "Honduran", label: "Honduran" },
    { value: "Hungarian", label: "Hungarian" },
    { value: "I-Kiribati", label: "I-Kiribati" },
    { value: "Icelander", label: "Icelander" },
    { value: "Indian", label: "Indian" },
    { value: "Indonesian", label: "Indonesian" },
    { value: "Iranian", label: "Iranian" },
    { value: "Iraqi", label: "Iraqi" },
    { value: "Irish", label: "Irish" },
    { value: "Israeli", label: "Israeli" },
    { value: "Italian", label: "Italian" },
    { value: "Ivorian", label: "Ivorian" },
    { value: "Jamaican", label: "Jamaican" },
    { value: "Japanese", label: "Japanese" },
    { value: "Jordanian", label: "Jordanian" },
    { value: "Kazakhstani", label: "Kazakhstani" },
    { value: "Kenyan", label: "Kenyan" },
    { value: "Kittian and Nevisian", label: "Kittian and Nevisian" },
    { value: "Kuwaiti", label: "Kuwaiti" },
    { value: "Kyrgyz", label: "Kyrgyz" },
    { value: "Laotian", label: "Laotian" },
    { value: "Latvian", label: "Latvian" },
    { value: "Lebanese", label: "Lebanese" },
    { value: "Liberian", label: "Liberian" },
    { value: "Libyan", label: "Libyan" },
    { value: "Liechtensteiner", label: "Liechtensteiner" },
    { value: "Lithuanian", label: "Lithuanian" },
    { value: "Luxembourger", label: "Luxembourger" },
    { value: "Macedonian", label: "Macedonian" },
    { value: "Malagasy", label: "Malagasy" },
    { value: "Malawian", label: "Malawian" },
    { value: "Malaysian", label: "Malaysian" },
    { value: "Maldivian", label: "Maldivian" },
    { value: "Malian", label: "Malian" },
    { value: "Maltese", label: "Maltese" },
    { value: "Marshallese", label: "Marshallese" },
    { value: "Mauritanian", label: "Mauritanian" },
    { value: "Mauritian", label: "Mauritian" },
    { value: "Mexican", label: "Mexican" },
    { value: "Micronesian", label: "Micronesian" },
    { value: "Moldovan", label: "Moldovan" },
    { value: "Monacan", label: "Monacan" },
    { value: "Mongolian", label: "Mongolian" },
    { value: "Moroccan", label: "Moroccan" },
    { value: "Mosotho", label: "Mosotho" },
    { value: "Motswana", label: "Motswana" },
    { value: "Mozambican", label: "Mozambican" },
    { value: "Namibian", label: "Namibian" },
    { value: "Nauruan", label: "Nauruan" },
    { value: "Nepalese", label: "Nepalese" },
    { value: "New Zealander", label: "New Zealander" },
    { value: "Ni-Vanuatu", label: "Ni-Vanuatu" },
    { value: "Nicaraguan", label: "Nicaraguan" },
    { value: "Nigerian", label: "Nigerian" },
    { value: "Nigerien", label: "Nigerien" },
    { value: "North Korean", label: "North Korean" },
    { value: "Northern Irish", label: "Northern Irish" },
    { value: "Norwegian", label: "Norwegian" },
    { value: "Omani", label: "Omani" },
    { value: "Pakistani", label: "Pakistani" },
    { value: "Palauan", label: "Palauan" },
    { value: "Panamanian", label: "Panamanian" },
    { value: "Papua New Guinean", label: "Papua New Guinean" },
    { value: "Paraguayan", label: "Paraguayan" },
    { value: "Peruvian", label: "Peruvian" },
    { value: "Polish", label: "Polish" },
    { value: "Portuguese", label: "Portuguese" },
    { value: "Qatari", label: "Qatari" },
    { value: "Romanian", label: "Romanian" },
    { value: "Russian", label: "Russian" },
    { value: "Rwandan", label: "Rwandan" },
    { value: "Saint Lucian", label: "Saint Lucian" },
    { value: "Salvadoran", label: "Salvadoran" },
    { value: "Samoan", label: "Samoan" },
    { value: "San Marinese", label: "San Marinese" },
    { value: "Sao Tomean", label: "Sao Tomean" },
    { value: "Saudi", label: "Saudi" },
    { value: "Scottish", label: "Scottish" },
    { value: "Senegalese", label: "Senegalese" },
    { value: "Serbian", label: "Serbian" },
    { value: "Seychellois", label: "Seychellois" },
    { value: "Sierra Leonean", label: "Sierra Leonean" },
    { value: "Singaporean", label: "Singaporean" },
    { value: "Slovakian", label: "Slovakian" },
    { value: "Slovenian", label: "Slovenian" },
    { value: "Solomon Islander", label: "Solomon Islander" },
    { value: "Somali", label: "Somali" },
    { value: "South African", label: "South African" },
    { value: "South Korean", label: "South Korean" },
    { value: "Spanish", label: "Spanish" },
    { value: "Sri Lankan", label: "Sri Lankan" },
    { value: "Sudanese", label: "Sudanese" },
    { value: "Surinamer", label: "Surinamer" },
    { value: "Swazi", label: "Swazi" },
    { value: "Swedish", label: "Swedish" },
    { value: "Swiss", label: "Swiss" },
    { value: "Syrian", label: "Syrian" },
    { value: "Taiwanese", label: "Taiwanese" },
    { value: "Tajik", label: "Tajik" },
    { value: "Tanzanian", label: "Tanzanian" },
    { value: "Thai", label: "Thai" },
    { value: "Togolese", label: "Togolese" },
    { value: "Tongan", label: "Tongan" },
    { value: "Trinidadian or Tobagonian", label: "Trinidadian or Tobagonian" },
    { value: "Tunisian", label: "Tunisian" },
    { value: "Turkish", label: "Turkish" },
    { value: "Tuvaluan", label: "Tuvaluan" },
    { value: "Ugandan", label: "Ugandan" },
    { value: "Ukrainian", label: "Ukrainian" },
    { value: "Uruguayan", label: "Uruguayan" },
    { value: "Uzbekistani", label: "Uzbekistani" },
    { value: "Venezuelan", label: "Venezuelan" },
    { value: "Vietnamese", label: "Vietnamese" },
    { value: "Welsh", label: "Welsh" },
    { value: "Yemenite", label: "Yemenite" },
    { value: "Zambian", label: "Zambian" },
    { value: "Zimbabwean", label: "Zimbabwean" },
  ],
};

export const storiesData = [
  {
    id: 1,
    age: "15-18",
    gender: "Men",
    sexuality: "Heterosexual",
    nationality: "Prefer not to say",
    shortDescription: "To some degree, social media saved my life",
    longDescription:
      "I was ready to end it all, I even planned on how to do it, how do get there etc. I had been ready for quite some time. Fortunately, it was pouring rain that night and I hadn’t gotten my drivers license yet so I decided to stay in bed one more day. I added some random girl on Snapchat and we’ve messaged the whole night, literally for like 10h straight. I listened as she talked shit about her parents and sport she was playing. I don’t remember almost anything from the whole conversation, it wasn’t really meaningful. She wasn’t even from my country, we had 8h time difference I believe, so she eventually said goodbye and went to sleep. We’ve never talked again. But next day I didn’t’ fell the need to kms anymore. I mean I was still severely depressed, probably should have been hospitalised by then, but somehow I got through. Shortly after that, I started following an account of a woman whose husband had failed a suicide attempt and was left paralysed with almost no brain activity left. This really shocked me, because I know, that it could have been me. And I know, it might be a little insincere, but I hated him for his selfishness. Now I know, that it’s not really selfishness, but I’d rather not share my thoughts on that topic here. But when I was watching the wife struggling everyday (she has become the man’s main caretaker and was drowning in medical bills bc welcome in America ofc). And I hated the idea of becoming such a burden for anybody. And the idea of being trapped in my body, loosing my mind. It scared the shit out of me. Later, I’ve started to feel shame, for allowing myself to even consider the possibility. Since then I’m still struggling with depression, some periods are better than others, but I haven’t gotten suicidal thoughts not once. I still sometimes wonder, whether the girl  I’ve talked to that night knows, that she probably saved my life. It’s funny how in her life I was just a meaningless guy, but she changed everything for me, but I guess these are the wonders of social media. Btw, as far as I know, the wife from the man remarried and the man is in some sort of nursing home, but they visit him regularly and care for him and seem quite happy :)",
  },

  {
    id: 2,
    age: "19-22",
    gender: "Non-binary",
    sexuality: "Asexual",
    nationality: "Polish",
    shortDescription:
      "If you have the knowledge on safe usage of social media, you can definitely make them a tool that will benefit you",
    longDescription:
      "I use social media for over 3 hours on a daily basis. I like how I can be true myself there. I found multiple wonderful friends online, they really helped me through the tough times. I think, it’s really important to have someone you can relate to – who has similar believes, values, interests to you. Someone that’s in a similar situation or have been going through, what you are going through right now. Especially when you’re just a teenager, that feels lonely and misunderstood even in a room full of people. Finding someone you can be on the same wavelength with gets easier with internet – social media platforms give us access to unlimited resources of people. But it’s not an easy task. Social media platforms are dangerous places, full of hatred and weirdos.",
  },

  {
    id: 3,
    age: "19-22",
    gender: "Woman",
    sexuality: "Pansexual",
    nationality: "Polish",
    shortDescription: "Social media helped me to develop my identity",
    longDescription:
      'I can say a lot of bad things about social media, but one thing is undeniable – shorten media broadens mind. I’m not proud of this, but when I was little, I used to be quite conservative, I was kinda homophobic, kinda racist, huge pick me girl. In 2020 (peak of pandemic) I started to use social media a lot, especially Tiktok. I could spend half a day on it, just scrolling brainlessly. Because of that, lots of different content started appearing on my For You Page and with time it got more and more progressive. Now I’m as far “left” as a reasonable human can get. That’s because as I started watching content that was out of my comfort zone, not in my perspective, and as I started listening to multiple amazing creators on there, I started to understand their point of view. With some things, I just decided, that their reasoning made more sense than my own. I’ve gained a lot of empathy and knowledge. With a lot of things I was indifferent beforehand, but now I stand for them with my whole heart. With few things I discovered new possibilities. For example when it comes to my sexuality, social media showed me that not being cis is normal and it’s okay. Then I realized, that most of female characters from movies, that I was so obsessed with were actually my first crushes (shout-out to Vanessa from Phineas and Ferb and Alex Russo from Wizard of Waverly Place"). Well, to sum up a little, do I think, that social media wasted a lot of my time and potential? Yes. But I also know, that I wouldn’t be, who I am today if it weren’t for the broad perspectives from Tiktok, to be honest, I’d probably still be unknowingly in the closet.',
  },

  {
    id: 4,
    age: "19-22",
    gender: "Women",
    sexuality: "Prefer not to say",
    nationality: "Polish",
    shortDescription:
      " It’s easier to stay connected with people with help of social media ",
    longDescription:
      "I have moved to another city so social media and sharing contents we share interests in helps us keep in touch and sparks conversation. Social media helps me and my friends, living both far and close, discover our shared interests and find new topics to discuss which often leads to further conversation. I think social media helped me a lot during covid lockdown, I got to keep up with others and their lives. As everyone found themselves in a similar situation, I've found a lot of motivation and goals because of others and got really immersed in my interests (which sounds like it's pretty separate from social medias but it's really not lol). I have found myself in a really supportive and wholesome community of fans of a music group that makes it their mission to help others. Both the groups message and the fans amongst which I found myself provided a lot of (indirect, because I don't like getting involved in social interactions support and understanding.",
  },

  {
    id: 5,
    age: "19-22",
    gender: "Woman",
    sexuality: "Prefer not to say",
    nationality: "Prefer not to say",
    shortDescription: "Social media helped me overcome my ed",
    longDescription:
      "During the pandemic, I developed severe problems with eating; I fell into an eating disorder and was able to survive on just water and apples for an entire week. I didn’t seek help because I didn’t see it as a problem, and due to the pandemic isolation, there weren’t really any opportunities for my environment to notice what was happening to me. The greatest help turned out to be a girl on TikTok who shared content about her journey with an eating disorder – she was going through recovery for a long time, and I followed her all throughout that period. Thanks to that, I became interested in the topic and, honestly, I recognized my own problem. I think that if it weren’t for that girl on TikTok, I might never have brought this topic up with anyone else for a very long time. I’m mostly sharing my emotions through social media, it’s easier to not be face to face with someone you’re telling some deep truth or story. The emotions i share in real life is only with my true loved ones who I can trust. Social media was some kind of my own diary by the time I was going through some deep deep things such as depression or stress, it really helped me to express myself",
  },
];
