export const navbarData = [
  {
    id: 1,
    navigationTitle: "ABOUT US",
    url: "/",
  },
  {
    id: 2,
    navigationTitle: "OUR STORIES",
    url: "/our-stories",
  },
  {
    id: 3,
    navigationTitle: "RESOURCES",
    url: "/contact",
  },
  {
    id: 4,
    navigationTitle: "SHARE YOUR STORY",
    url: "/your-story",
  },
];

export const footerData = {
  author: "MINDFULLMEDIA",
};

export const teamMembers = [
  {
    id: 1,
    name: "John",
    surname: "Doe",
    image: "team-members/member3.jpg",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas porttitor congue massa. Fusce posuere, magna sed pulvinar ultricies, purus lectus malesuada libero, sit amet commodo magna eros quis urna. Nunc viverra imperdiet enim. Fusce est. Vivamus a tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin pharetra nonummy pede",
  },
  {
    id: 2,
    name: "Jane",
    surname: "Doe",
    image: "team-members/member2.jpg",
    description: "Bla bla bla",
  },
  {
    id: 3,
    name: "John",
    surname: "Smith",
    image: "team-members/member3.jpg",
    description: "Bl bl bl",
  },
];

export const filtersData = {
  age: [
    { value: "Prefer not to say", label: "Prefer not to say" },
    { value: "0-18", label: "0-18" },
    { value: "19-25", label: "19-25" },
    { value: "26-35", label: "26-35" },
    { value: "36-50", label: "36-50" },
    { value: "50+", label: "50+" },
  ],
  gender: [
    { value: "Prefer not to say", label: "Prefer not to say" },
    { value: "Male", label: "Male" },
    { value: "Female", label: "Female" },
    { value: "Non-binary", label: "Non-binary" },
  ],
  race: [
    { value: "Prefer not to say", label: "Prefer not to say" },
    { value: "White", label: "White" },
    { value: "Black", label: "Black" },
    { value: "Asian", label: "Asian" },
    { value: "Latino", label: "Latino" },
    { value: "Middle Eastern", label: "Middle Eastern" },
  ],
  sexuality: [
    { value: "Prefer not to say", label: "Prefer not to say" },
    { value: "Straight", label: "Straight" },
    { value: "Gay", label: "Gay" },
    { value: "Bisexual", label: "Bisexual" },
    { value: "Pansexual", label: "Pansexual" },
    { value: "Asexual", label: "Asexual" },
  ],
  nationality: [
    { value: "Prefer not to say", label: "Prefer not to say" },
    { value: "Afghan", label: "Afghan" },
    { value: "Albanian", label: "Albanian" },
    { value: "Algerian", label: "Algerian" },
    { value: "American", label: "American" },
    { value: "Andorran", label: "Andorran" },
    { value: "Angolan", label: "Angolan" },
    { value: "Antiguans", label: "Antiguans" },
    { value: "Argentinean", label: "Argentinean" },
    { value: "Armenian", label: "Armenian" },
    { value: "Australian", label: "Australian" },
    { value: "Austrian", label: "Austrian" },
    { value: "Azerbaijani", label: "Azerbaijani" },
    { value: "Bahamian", label: "Bahamian" },
    { value: "Bahraini", label: "Bahraini" },
    { value: "Bangladeshi", label: "Bangladeshi" },
    { value: "Barbadian", label: "Barbadian" },
    { value: "Barbudans", label: "Barbudans" },
    { value: "Batswana", label: "Batswana" },
    { value: "Belarusian", label: "Belarusian" },
    { value: "Belgian", label: "Belgian" },
    { value: "Belizean", label: "Belizean" },
    { value: "Beninese", label: "Beninese" },
    { value: "Bhutanese", label: "Bhutanese" },
    { value: "Bolivian", label: "Bolivian" },
    { value: "Bosnian", label: "Bosnian" },
    { value: "Brazilian", label: "Brazilian" },
    { value: "British", label: "British" },
    { value: "Bruneian", label: "Bruneian" },
    { value: "Bulgarian", label: "Bulgarian" },
    { value: "Burkinabe", label: "Burkinabe" },
    { value: "Burmese", label: "Burmese" },
    { value: "Burundian", label: "Burundian" },
    { value: "Cambodian", label: "Cambodian" },
    { value: "Cameroonian", label: "Cameroonian" },
    { value: "Canadian", label: "Canadian" },
    { value: "Cape Verdean", label: "Cape Verdean" },
    { value: "Central African", label: "Central African" },
    { value: "Chadian", label: "Chadian" },
    { value: "Chilean", label: "Chilean" },
    { value: "Chinese", label: "Chinese" },
    { value: "Colombian", label: "Colombian" },
    { value: "Comoran", label: "Comoran" },
    { value: "Congolese", label: "Congolese" },
    { value: "Costa Rican", label: "Costa Rican" },
    { value: "Croatian", label: "Croatian" },
    { value: "Cuban", label: "Cuban" },
    { value: "Cypriot", label: "Cypriot" },
    { value: "Czech", label: "Czech" },
    { value: "Danish", label: "Danish" },
    { value: "Djibouti", label: "Djibouti" },
    { value: "Dominican", label: "Dominican" },
    { value: "Dutch", label: "Dutch" },
    { value: "East Timorese", label: "East Timorese" },
    { value: "Ecuadorean", label: "Ecuadorean" },
    { value: "Egyptian", label: "Egyptian" },
    { value: "Emirian", label: "Emirian" },
    { value: "Equatorial Guinean", label: "Equatorial Guinean" },
    { value: "Eritrean", label: "Eritrean" },
    { value: "Estonian", label: "Estonian" },
    { value: "Ethiopian", label: "Ethiopian" },
    { value: "Fijian", label: "Fijian" },
    { value: "Filipino", label: "Filipino" },
    { value: "Finnish", label: "Finnish" },
    { value: "French", label: "French" },
    { value: "Gabonese", label: "Gabonese" },
    { value: "Gambian", label: "Gambian" },
    { value: "Georgian", label: "Georgian" },
    { value: "German", label: "German" },
    { value: "Ghanaian", label: "Ghanaian" },
    { value: "Greek", label: "Greek" },
    { value: "Grenadian", label: "Grenadian" },
    { value: "Guatemalan", label: "Guatemalan" },
    { value: "Guinea-Bissauan", label: "Guinea-Bissauan" },
    { value: "Guinean", label: "Guinean" },
    { value: "Guyanese", label: "Guyanese" },
    { value: "Haitian", label: "Haitian" },
    { value: "Herzegovinian", label: "Herzegovinian" },
    { value: "Honduran", label: "Honduran" },
    { value: "Hungarian", label: "Hungarian" },
    { value: "I-Kiribati", label: "I-Kiribati" },
    { value: "Icelander", label: "Icelander" },
    { value: "Indian", label: "Indian" },
    { value: "Indonesian", label: "Indonesian" },
    { value: "Iranian", label: "Iranian" },
    { value: "Iraqi", label: "Iraqi" },
    { value: "Irish", label: "Irish" },
    { value: "Israeli", label: "Israeli" },
    { value: "Italian", label: "Italian" },
    { value: "Ivorian", label: "Ivorian" },
    { value: "Jamaican", label: "Jamaican" },
    { value: "Japanese", label: "Japanese" },
    { value: "Jordanian", label: "Jordanian" },
    { value: "Kazakhstani", label: "Kazakhstani" },
    { value: "Kenyan", label: "Kenyan" },
    { value: "Kittian and Nevisian", label: "Kittian and Nevisian" },
    { value: "Kuwaiti", label: "Kuwaiti" },
    { value: "Kyrgyz", label: "Kyrgyz" },
    { value: "Laotian", label: "Laotian" },
    { value: "Latvian", label: "Latvian" },
    { value: "Lebanese", label: "Lebanese" },
    { value: "Liberian", label: "Liberian" },
    { value: "Libyan", label: "Libyan" },
    { value: "Liechtensteiner", label: "Liechtensteiner" },
    { value: "Lithuanian", label: "Lithuanian" },
    { value: "Luxembourger", label: "Luxembourger" },
    { value: "Macedonian", label: "Macedonian" },
    { value: "Malagasy", label: "Malagasy" },
    { value: "Malawian", label: "Malawian" },
    { value: "Malaysian", label: "Malaysian" },
    { value: "Maldivian", label: "Maldivian" },
    { value: "Malian", label: "Malian" },
    { value: "Maltese", label: "Maltese" },
    { value: "Marshallese", label: "Marshallese" },
    { value: "Mauritanian", label: "Mauritanian" },
    { value: "Mauritian", label: "Mauritian" },
    { value: "Mexican", label: "Mexican" },
    { value: "Micronesian", label: "Micronesian" },
    { value: "Moldovan", label: "Moldovan" },
    { value: "Monacan", label: "Monacan" },
    { value: "Mongolian", label: "Mongolian" },
    { value: "Moroccan", label: "Moroccan" },
    { value: "Mosotho", label: "Mosotho" },
    { value: "Motswana", label: "Motswana" },
    { value: "Mozambican", label: "Mozambican" },
    { value: "Namibian", label: "Namibian" },
    { value: "Nauruan", label: "Nauruan" },
    { value: "Nepalese", label: "Nepalese" },
    { value: "New Zealander", label: "New Zealander" },
    { value: "Ni-Vanuatu", label: "Ni-Vanuatu" },
    { value: "Nicaraguan", label: "Nicaraguan" },
    { value: "Nigerian", label: "Nigerian" },
    { value: "Nigerien", label: "Nigerien" },
    { value: "North Korean", label: "North Korean" },
    { value: "Northern Irish", label: "Northern Irish" },
    { value: "Norwegian", label: "Norwegian" },
    { value: "Omani", label: "Omani" },
    { value: "Pakistani", label: "Pakistani" },
    { value: "Palauan", label: "Palauan" },
    { value: "Panamanian", label: "Panamanian" },
    { value: "Papua New Guinean", label: "Papua New Guinean" },
    { value: "Paraguayan", label: "Paraguayan" },
    { value: "Peruvian", label: "Peruvian" },
    { value: "Polish", label: "Polish" },
    { value: "Portuguese", label: "Portuguese" },
    { value: "Qatari", label: "Qatari" },
    { value: "Romanian", label: "Romanian" },
    { value: "Russian", label: "Russian" },
    { value: "Rwandan", label: "Rwandan" },
    { value: "Saint Lucian", label: "Saint Lucian" },
    { value: "Salvadoran", label: "Salvadoran" },
    { value: "Samoan", label: "Samoan" },
    { value: "San Marinese", label: "San Marinese" },
    { value: "Sao Tomean", label: "Sao Tomean" },
    { value: "Saudi", label: "Saudi" },
    { value: "Scottish", label: "Scottish" },
    { value: "Senegalese", label: "Senegalese" },
    { value: "Serbian", label: "Serbian" },
    { value: "Seychellois", label: "Seychellois" },
    { value: "Sierra Leonean", label: "Sierra Leonean" },
    { value: "Singaporean", label: "Singaporean" },
    { value: "Slovakian", label: "Slovakian" },
    { value: "Slovenian", label: "Slovenian" },
    { value: "Solomon Islander", label: "Solomon Islander" },
    { value: "Somali", label: "Somali" },
    { value: "South African", label: "South African" },
    { value: "South Korean", label: "South Korean" },
    { value: "Spanish", label: "Spanish" },
    { value: "Sri Lankan", label: "Sri Lankan" },
    { value: "Sudanese", label: "Sudanese" },
    { value: "Surinamer", label: "Surinamer" },
    { value: "Swazi", label: "Swazi" },
    { value: "Swedish", label: "Swedish" },
    { value: "Swiss", label: "Swiss" },
    { value: "Syrian", label: "Syrian" },
    { value: "Taiwanese", label: "Taiwanese" },
    { value: "Tajik", label: "Tajik" },
    { value: "Tanzanian", label: "Tanzanian" },
    { value: "Thai", label: "Thai" },
    { value: "Togolese", label: "Togolese" },
    { value: "Tongan", label: "Tongan" },
    { value: "Trinidadian or Tobagonian", label: "Trinidadian or Tobagonian" },
    { value: "Tunisian", label: "Tunisian" },
    { value: "Turkish", label: "Turkish" },
    { value: "Tuvaluan", label: "Tuvaluan" },
    { value: "Ugandan", label: "Ugandan" },
    { value: "Ukrainian", label: "Ukrainian" },
    { value: "Uruguayan", label: "Uruguayan" },
    { value: "Uzbekistani", label: "Uzbekistani" },
    { value: "Venezuelan", label: "Venezuelan" },
    { value: "Vietnamese", label: "Vietnamese" },
    { value: "Welsh", label: "Welsh" },
    { value: "Yemenite", label: "Yemenite" },
    { value: "Zambian", label: "Zambian" },
    { value: "Zimbabwean", label: "Zimbabwean" },
  ],
};

export const storiesData = [
  {
    id: 1,
    age: "26-35",
    gender: "Female",
    race: "Asian",
    sexuality: "Bisexual",
    nationality: "Afghan",
    shortDescription: "Freelance graphic designer from Tokyo.",
    longDescription:
      "Aiko is a creative professional who specializes in branding and digital illustration. She enjoys traveling, minimalist design, and often volunteers for local art education programs in Japan.",
  },
  {
    id: 2,
    age: "36-50",
    gender: "Male",
    race: "Black",
    sexuality: "Straight",
    nationality: "American",
    shortDescription: "High school history teacher and father of two.",
    longDescription:
      "Marcus has been teaching for over 15 years and is passionate about making history accessible and engaging for all students. Outside of school, he coaches youth basketball and writes historical fiction.",
  },
  {
    id: 3,
    age: "26-35",
    gender: "Non-binary",
    race: "White",
    sexuality: "Pansexual",
    nationality: "Canadian",
    shortDescription: "Tech entrepreneur and startup mentor.",
    longDescription:
      "Jordan founded their first company at age 23 and now works as a mentor for tech startups in Vancouver. They advocate for inclusive innovation and enjoy hiking in British Columbia's forests.",
  },
  {
    id: 4,
    age: "19-25",
    gender: "Male",
    race: "Latino",
    sexuality: "Gay",
    nationality: "Mexican",
    shortDescription: "Aspiring actor with a passion for musical theatre.",
    longDescription:
      "Diego moved to Mexico City to pursue his acting career and has performed in several local productions. He's a classically trained singer and hopes to one day appear on Broadway.",
  },
  {
    id: 5,
    age: "26-35",
    gender: "Female",
    race: "Middle Eastern",
    sexuality: "Asexual",
    nationality: "Egyptian",
    shortDescription: "Software engineer and open-source contributor.",
    longDescription:
      "Leila specializes in backend development and is an advocate for women in STEM. She contributes to open-source projects and runs a mentorship program for young girls interested in coding in Cairo.",
  },
  {
    id: 6,
    age: "0-18",
    gender: "Non-binary",
    race: "Latino",
    sexuality: "Pansexual",
    nationality: "Mexican",
    shortDescription: "High school student and robotics enthusiast.",
    longDescription:
      "Alexis is part of their school’s robotics team in Guadalajara. They enjoy coding in Python and dream of becoming a mechatronics engineer. They often volunteer at local STEM workshops for children.",
  },
  {
    id: 7,
    age: "50+",
    gender: "Male",
    race: "White",
    sexuality: "Straight",
    nationality: "Canadian",
    shortDescription: "Retired firefighter turned nature photographer.",
    longDescription:
      "Robert spent 30 years serving his community in Alberta. Now retired, he travels across Canada capturing wildlife with his camera and advocates for forest conservation.",
  },
  {
    id: 8,
    age: "19-25",
    gender: "Female",
    race: "Asian",
    sexuality: "Gay",
    nationality: "Japanese",
    shortDescription: "University student studying marine biology.",
    longDescription:
      "Miyu is passionate about ocean conservation and spends her summers researching coral reefs in Okinawa. She's active in campus LGBTQ+ advocacy and enjoys scuba diving.",
  },
  {
    id: 9,
    age: "36-50",
    gender: "Non-binary",
    race: "Middle Eastern",
    sexuality: "Asexual",
    nationality: "Egyptian",
    shortDescription: "Librarian and historical archivist in Alexandria.",
    longDescription:
      "Samir works to digitize rare manuscripts and promote access to public knowledge. They organize educational events on Egypt’s cultural heritage and enjoy quiet evenings reading poetry.",
  },
  {
    id: 10,
    age: "0-18",
    gender: "Female",
    race: "Black",
    sexuality: "Straight",
    nationality: "American",
    shortDescription: "Aspiring pianist and youth activist.",
    longDescription:
      "Tiana, a 17-year-old from Atlanta, balances schoolwork with music and social justice projects. She's performed at community events and dreams of attending a conservatory in New York.",
  },
  {
    id: 11,
    age: "19-25",
    gender: "Male",
    race: "White",
    sexuality: "Bisexual",
    nationality: "Canadian",
    shortDescription: "Engineering student and hockey player.",
    longDescription:
      "Liam studies mechanical engineering in Toronto and plays defense on his university's hockey team. He's also part of an LGBTQ+ inclusion initiative for student athletes.",
  },
  {
    id: 12,
    age: "50+",
    gender: "Female",
    race: "Latino",
    sexuality: "Straight",
    nationality: "Mexican",
    shortDescription: "Retired chef and community gardener.",
    longDescription:
      "Maria spent over 40 years working in restaurants across Mexico. Now, she teaches cooking classes and maintains a garden that provides fresh produce to local families.",
  },
  {
    id: 13,
    age: "36-50",
    gender: "Female",
    race: "Asian",
    sexuality: "Gay",
    nationality: "Japanese",
    shortDescription: "Architect passionate about sustainable design.",
    longDescription:
      "Yumi specializes in eco-friendly architecture and has led several projects promoting green buildings in Osaka. She also mentors young women entering the field.",
  },
  {
    id: 14,
    age: "26-35",
    gender: "Male",
    race: "Middle Eastern",
    sexuality: "Pansexual",
    nationality: "Egyptian",
    shortDescription: "Documentary filmmaker focused on human rights.",
    longDescription:
      "Omar travels the Middle East to film stories on education and migration. His work has been featured at international festivals and aims to amplify marginalized voices.",
  },
  {
    id: 15,
    age: "0-18",
    gender: "Female",
    race: "White",
    sexuality: "Asexual",
    nationality: "American",
    shortDescription: "Young poet with a love for astronomy.",
    longDescription:
      "Sophie is a high school student in Vermont who writes poetry about stars and science. She's won several youth writing contests and aspires to become an astrophysicist.",
  },
  {
    id: 16,
    age: "26-35",
    gender: "Non-binary",
    race: "Black",
    sexuality: "Bisexual",
    nationality: "Canadian",
    shortDescription: "Community organizer and spoken word artist.",
    longDescription:
      "Toni works with youth in Toronto to promote civic engagement and artistic expression. They host regular open mic nights and are active in anti-racism education.",
  },
  {
    id: 17,
    age: "19-25",
    gender: "Female",
    race: "Middle Eastern",
    sexuality: "Straight",
    nationality: "Egyptian",
    shortDescription: "Medical student passionate about women's health.",
    longDescription:
      "Fatima is studying medicine in Cairo and volunteers at clinics focused on maternal care. She hopes to become a gynecologist serving underserved communities.",
  },
  {
    id: 18,
    age: "50+",
    gender: "Non-binary",
    race: "Asian",
    sexuality: "Gay",
    nationality: "Japanese",
    shortDescription: "Retired professor and tea ceremony instructor.",
    longDescription:
      "Kenta taught philosophy at a Tokyo university and now teaches traditional tea ceremony. They advocate for elder LGBTQ+ representation in cultural spaces.",
  },
  {
    id: 19,
    age: "0-18",
    gender: "Male",
    race: "Black",
    sexuality: "Straight",
    nationality: "American",
    shortDescription: "Middle school chess champion.",
    longDescription:
      "Jamari is a 13-year-old prodigy from Chicago who has won state-level chess tournaments. He's working on a YouTube channel to teach chess to other kids in his neighborhood.",
  },
  {
    id: 20,
    age: "36-50",
    gender: "Male",
    race: "White",
    sexuality: "Asexual",
    nationality: "Canadian",
    shortDescription: "IT consultant and amateur musician.",
    longDescription:
      "Daniel works remotely from Montreal and spends his evenings composing instrumental music. He's part of an asexual advocacy group focused on workplace inclusivity.",
  },
];
